[build]
base_image = "node:16"  # Puedes cambiar esto a la versión de Node.js que estés usando

[phases.setup]
commands = [
  "cd back && npm install"
]

[phases.build]
commands = [
  "cd back"
]

[start]
commands = [
  "node app.js"
]
